version: '3'

services:
  mysql-master:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: masterDb
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"       # Giới hạn tối đa 50% CPU
          memory: "512M"     # Giới hạn tối đa 512MB RAM
        reservations:
          cpus: "0.2"       # Đảm bảo 20% CPU có sẵn cho container
          memory: "256M"     # Đảm bảo ít nhất 256MB RAM có sẵn


  mysql-slave:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: slaveDb
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"       # Giới hạn tối đa 50% CPU
          memory: "512M"     # Giới hạn tối đa 512MB RAM
        reservations:
          cpus: "0.2"       # Đảm bảo 20% CPU có sẵn cho container
          memory: "256M"     # Đảm bảo ít nhất 256MB RAM có sẵn


  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-master
      - mysql-slave
    restart: always
    environment:
      - SPRING_DATASOURCE_MASTER_URL=jdbc:mysql://mysql-master:3306/masterDb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_SLAVE_URL=jdbc:mysql://mysql-slave:3306/slaveDb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "1.0"       # Giới hạn 100% CPU
          memory: "1G"       # Giới hạn 1GB RAM
        reservations:
          cpus: "0.5"       # Đảm bảo 50% CPU có sẵn
          memory: "512M"     # Đảm bảo ít nhất 512MB RAM có sẵn
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Cổng chính mà Nginx sẽ nghe
    depends_on:
      - spring-app
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.2"       # Giới hạn 20% CPU
          memory: "128M"     # Giới hạn 128MB RAM
        reservations:
          cpus: "0.1"       # Đảm bảo 10% CPU có sẵn
          memory: "64M"      # Đảm bảo ít nhất 64MB RAM có sẵn

networks:
  app-network: